#!/usr/bin/env python3
import re
import sys
import subprocess
import json
from pathlib import Path

def extract_nodes():
    """Extract node list from V2EX planes page"""
    try:
        # Fetch the planes page
        import urllib.request
        import urllib.error
        url = "https://www.v2ex.com/planes"
        req = urllib.request.Request(url, headers={'User-Agent': 'Mozilla/5.0'})
        response = urllib.request.urlopen(req)
        html = response.read().decode('utf-8')
    except ImportError:
        # Fallback to curl if urllib not available
        result = subprocess.run(
            ['curl', '-s', 'https://www.v2ex.com/planes'],
            capture_output=True,
            text=True
        )
        html = result.stdout
    
    # Extract nodes with pattern: href="/go/NODE_NAME" class="item_node">NODE_TITLE</a>
    # Use regex to capture both node name and title
    pattern = r'href="/go/([^"]+)"[^>]*>([^<]+)</a>'
    matches = re.findall(pattern, html)
    
    # Filter for item_node class (more specific)
    pattern2 = r'href="/go/([^"]+)" class="item_node">([^<]+)</a>'
    matches2 = re.findall(pattern2, html)
    
    # Use the more specific matches if found
    if matches2:
        nodes = matches2
    else:
        nodes = matches
    
    # Remove duplicates while preserving order
    seen = set()
    unique_nodes = []
    for node_name, node_title in nodes:
        if node_name not in seen:
            seen.add(node_name)
            unique_nodes.append((node_name, node_title))
    
    return unique_nodes

def generate_rust_code(nodes):
    """Generate Rust vector initialization code"""
    lines = []
    lines.append('        let nodes = vec![')
    for i, (node_name, node_title) in enumerate(nodes):
        # Escape quotes in node_title
        escaped_title = node_title.replace('"', '\\"')
        line = f'            ("{node_name}".to_string(), "{escaped_title}".to_string()),'
        lines.append(line)
    lines.append('        ];')
    return '\n'.join(lines)

def generate_rust_module(nodes):
    """Generate a complete Rust module with node list"""
    lines = []
    lines.append('//! Node definitions extracted from V2EX planes page')
    lines.append('//! Generated by extract_nodes.py')
    lines.append('')
    lines.append('/// Get the complete list of V2EX nodes (name, title)')
    lines.append('pub fn get_all_nodes() -> Vec<(String, String)> {')
    lines.append('    vec![')
    for i, (node_name, node_title) in enumerate(nodes):
        # Escape quotes in node_title
        escaped_title = node_title.replace('"', '\\"').replace('\\', '\\\\')
        line = f'        ("{node_name}".to_string(), "{escaped_title}".to_string()),'
        lines.append(line)
    lines.append('    ]')
    lines.append('}')
    return '\n'.join(lines)

def generate_all_nodes_rust(nodes):
    """Generate Rust code for all_nodes vector"""
    lines = []
    lines.append('    let all_nodes = vec![')
    for i, (node_name, node_title) in enumerate(nodes):
        # Escape quotes and backslashes in node_title
        escaped_title = node_title.replace('\\', '\\\\').replace('"', '\\"')
        line = f'        ("{node_name}".to_string(), "{escaped_title}".to_string()),'
        lines.append(line)
    lines.append('    ];')
    return '\n'.join(lines)

def main():
    nodes = extract_nodes()
    
    print(f"Found {len(nodes)} nodes")
    
    # Generate Rust code for all_nodes
    rust_code = generate_all_nodes_rust(nodes)
    print("\n\nRust code for all_nodes in App::new():")
    print(rust_code)
    
    # Also generate favorite nodes (first 9)
    favorite_nodes = nodes[:9]
    print("\n\nFavorite nodes (first 9):")
    for i, (name, title) in enumerate(favorite_nodes, 1):
        print(f"{i}. {name:20} - {title}")
    
    # Save to file
    output_file = Path("nodes.json")
    with open(output_file, 'w', encoding='utf-8') as f:
        json.dump(nodes, f, ensure_ascii=False, indent=2)
    print(f"\nNode list saved to {output_file}")

if __name__ == "__main__":
    main()