(set! "topics-per-page" 20)
(set! "replies-per-page" 20)
(set! "auto-refresh-interval" 0)
(set! "key-sequence-timeout" 1000)
(set! "theme" "dark")
(set! "timestamp-format" "relative")
(set! "initial-view" "topic-list")

(bind "C-c" "quit-immediate")
(bind "q" "remove-from-history")
(bind "ESC" "remove-from-history")
(bind "l" "history-back")
(bind "r" "history-forward")
(bind "g" "refresh")
(bind "?" "show-help")
(bind "a" "go-to-aggregate")
(bind "m" "go-to-notifications")
(bind "u" "go-to-profile")
(bind "s" "go-to-node-select")

(define-key "view-topic-list" "t" "open-topic")
(define-key "view-topic-list" "RET" "open-topic")
(define-key "view-topic-list" "+" "load-more-topics")
(define-key "view-topic-list" "o" "open-in-browser")
(define-key "view-topic-list" "s" "select-node")

(define-key "view-topic-detail" "t" "toggle-replies")
(define-key "view-topic-detail" "o" "open-in-browser")
(define-key "view-topic-detail" "f" "enter-link-mode")
(define-key "view-topic-detail" "+" "load-more-replies")

(define-key "mode-replies" "n" "next-reply")
(define-key "mode-replies" "p" "previous-reply")
(define-key "mode-replies" "+" "load-more-replies")
(define-key "mode-replies" "<" "first-item")
(define-key "mode-replies" ">" "last-item")

(define-key "mode-link-selection" "a" "link-select-a")
(define-key "mode-link-selection" "o" "link-select-o")
(define-key "mode-link-selection" "e" "link-select-e")
(define-key "mode-link-selection" "u" "link-select-u")
(define-key "mode-link-selection" "i" "link-select-i")
(define-key "mode-link-selection" "d" "link-select-d")
(define-key "mode-link-selection" "h" "link-select-h")
(define-key "mode-link-selection" "t" "link-select-t")
(define-key "mode-link-selection" "n" "link-select-n")
(define-key "mode-link-selection" "s" "link-select-s")
(define-key "mode-link-selection" "ESC" "exit-link-mode")

(define-key "view-aggregate" "Enter" "open-aggregate-item")
(define-key "view-aggregate" "o" "open-in-browser")
(define-key "view-aggregate" "g" "refresh-aggregate")

(define-key "view-aggregate" "t" "switch-tab-tech")
(define-key "view-aggregate" "c" "switch-tab-creative")
(define-key "view-aggregate" "k" "switch-tab-play")
(define-key "view-aggregate" "a" "switch-tab-apple")
(define-key "view-aggregate" "j" "switch-tab-jobs")
(define-key "view-aggregate" "d" "switch-tab-deals")
(define-key "view-aggregate" "y" "switch-tab-city")
(define-key "view-aggregate" "z" "switch-tab-qna")
(define-key "view-aggregate" "i" "switch-tab-index")
