#!/usr/bin/env python3
"""
Admin script: Generate Rust node definitions from JSON

This script takes the pre-generated nodes.json file and creates the
Rust module src/nodes.rs with all V2EX node definitions for the v2ex-tui project.

Usage:
    python scripts/generate_nodes_rs.py

Input:
    - scripts/nodes.json: Node data file (generated by extract_nodes.py)

Output:
    - src/nodes.rs: Complete Rust module with node definitions
"""

import json
import re
from pathlib import Path

# Load nodes from JSON (in scripts/ directory)
script_dir = Path(__file__).parent
json_file = script_dir / 'nodes.json'

with open(json_file, 'r', encoding='utf-8') as f:
    nodes = json.load(f)

# Generate Rust module file
lines = []
lines.append('//! Node definitions extracted from V2EX planes page')
lines.append('//! Generated by generate_nodes_rs.py')
lines.append('//! Total nodes: {}'.format(len(nodes)))
lines.append('')
lines.append('use std::sync::OnceLock;')
lines.append('')
lines.append('/// Get all available V2EX nodes')
lines.append('#[rustfmt::skip]')
lines.append('pub fn get_all_nodes() -> &\'static [(String, String)] {')
lines.append('    static NODES: OnceLock<Vec<(String, String)>> = OnceLock::new();')
lines.append('    NODES.get_or_init(|| {')
lines.append('        vec![')

# Add all nodes
for i, (node_name, node_title) in enumerate(nodes):
    # Escape quotes, backslashes, and invisible characters
    escaped_title = node_title.replace('\\', '\\\\').replace('"', '\\"')
    # Escape word joiner (U+2060) and other invisible characters for clippy
    escaped_title = escaped_title.replace('\u2060', '\\u{2060}')
    line = f'            ("{node_name}".to_string(), "{escaped_title}".to_string()),'
    lines.append(line)
    
    # Add comment every 100 nodes
    if (i + 1) % 100 == 0:
        lines.append(f'            // ... {i + 1} nodes ...')

lines.append('        ]')
lines.append('    })')
lines.append('}')

# Write to file with trailing newline
output_file = Path('src/nodes.rs')
with open(output_file, 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines))
    f.write('\n')  # Add trailing newline

print(f'Generated {output_file} with {len(nodes)} nodes')